### DISCUSSION TITLE
Securing SSH access to warpgate

### DISCUSSION THREAD

**Discussion by jeffbrl** [warp-tech/warpgate#129] [Q&A] [answered]
What is the recommended way to secure warpgate from unwanted users connecting via SSH? By following the Getting Started guide, I believe you end up with an insecure setup in which anyone who can guess the targets can SSH to them.

**Comment by Eugeny** [comment]
No, targets are only accessible for authenticated users when their assigned roles match the target's own. The role list is set through `targets.<target>.allowed_roles` here: https://github.com/warp-tech/warpgate/wiki/Adding-an-SSH-target#connection-setup

Warpgate doesn't include any way to access targets anonymously.

**Reply by jeffbrl** [reply]
Eugeny, I appreciate the reply and your open sourcing of this software. Admittedly, I do not understand the authentication here. 

Here is the target configuration in my warpgate config.

```
---
targets:
  - name: web-admin
    allow_roles:
      - "warpgate:admin"
    web_admin: {}
  - name: vm01
    allow_roles:
      - "warpgate:admin"
    ssh:
      host: 192.168.0.10
      username: jeffl
```

I am able to ssh without authentication.

```
jeffl@piholevm:~$ ssh admin:vm01@192.168.0.100 -p 2222
 Warpgate  Selected target: vm01
 Warpgate  Host key (ssh-ed25519): <redacted>
 ✓ Warpgate connected

Welcome to Ubuntu 20.04.4 LTS (GNU/Linux 5.15.35-1-pve x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
Last login: Wed Jun  8 12:50:04 2022 from 192.168.0.1
jeffl@vm01 ~ []$
```

My expectation is that I would be prompted for the warpgate admin password. What am I not understanding correctly?

**Reply by Eugeny** [reply]
Could you please post the whole config file (or send it to me privately at x@null.page)?

**Reply by jeffbrl** [reply]
```
---
targets:
  - name: web-admin
    allow_roles:
      - "warpgate:admin"
    web_admin: {}
  - name: vm01
    allow_roles:
      - "warpgate:admin"
    ssh:
      host: 192.168.0.10
      username: jeffl
users:
  - username: admin
    credentials:
      - type: password
        hash: "<redacted>"
    roles:
      - "warpgate:admin"
roles:
  - name: "warpgate:admin"
recordings:
  enable: true
  path: /var/lib/warpgate/recordings
web_admin:
  enable: true
  listen: "0.0.0.0:8888"
  certificate: /var/lib/warpgate/web-admin.certificate.pem
  key: /var/lib/warpgate/web-admin.key.pem
database_url: "sqlite:/var/lib/warpgate/db"
ssh:
  listen: "0.0.0.0:2222"
  keys: /var/lib/warpgate/ssh-keys
  client_key: "./client_key"
log:
  retention: 7days
  send_to: ~
```
