### DISCUSSION TITLE
SSO auth with Github?

### DISCUSSION THREAD

**Discussion by soakes** [warp-tech/warpgate#991] [Q&A] [answered]
Does this support Github auth?

I have checked the following url and pritty much has the main ones covered apart from Github which suprises me as most other apps support this out of the box.
 
https://github.com/warp-tech/warpgate/wiki/SSO-Authentication

Is there away to add this via custom?

**Comment by Eugeny** [comment, marked as answer]
Of course, you can use any OIDC provider via `custom`

**Reply by soakes** [reply]
Thank you.  I assume the issuer url would be `github.com`?

**Reply by soakes** [reply]
nvm, believe ive sussed it, thank you for your confirmation.

```
sso_providers:
- name: github
   label: GitHub SSO
   provider:
     type: custom
     client_id: <your-github-client-id>
     client_secret: <your-github-client-secret>
     issuer_url: https://github.com
     scopes: ["email"]
```
