### ISSUE TITLE
With a self-hosted oidc server, no error logs are reported and the browser returns status code 404

### ISSUE THREAD

**Issue by vitaaaaa1** [warp-tech/warpgate#1074]
hello everyone，I tried to configure oidc.However, after I clicked on oidc to log in, the browser and the program log did not respond,The status code of the browser console,
```
https://warpgate.com:8888/@warpgate/api/sso/providers/oidc-custom/start
# 500 Internal Server Error
https://warpgate.com:8888/@warpgate/api/auth/state
# 404 Not Found
```
Other than that there are no error messages
My oidc provider is Authentik
And this is my is my program configuration file
```
- name: oidc-custom
  label: Custom SSO
  provider:
    type: custom
    client_id: xxx
    client_secret: xxxx
    issuer_url: https://authentik.xxx.com/application/o/warpgate/.well-known/openid-configuration
    scopes:
      - email
      - openid
```
These are my oidc provider information
```
OpenID Configuration URL 
https://authentik.xxx.com/application/o/warpgate/.well-known/openid-configuration
OpenID Configuration Issuer
https://authentik.xxx.com/application/o/warpgate/
Authorize URL
https://authentik.xxx.com/application/o/authorize/
Redirect URIs
https://warpgate.com:8888/@warpgate/api/sso/return
```

Someone can help me

**Comment by Eugeny** [comment]
Try using the URL without the `/.well-known/openid-configuration` suffix and if that doesn't help, run Warpgate with `--debug` and grab the output when trying to log in.

**Comment by vitaaaaa1** [comment]
> --debug
I'm using docker compose to start my application, where should I add the debug parameter
```
version: '3'
services:
  warpgate:
    image: ghcr.io/warp-tech/warpgate
    ports:
      - 2222:2222
      - 8888:8888
      - 33306:33306
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
```

**Comment by Eugeny** [comment]
Add the `command` like this:

```yaml
version: '3'
services:
  warpgate:
    image: ghcr.io/warp-tech/warpgate
    ports:
      - 2222:2222
      - 8888:8888
      - 33306:33306
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
    command: ['--debug', 'run']
```

**Comment by vitaaaaa1** [comment]
```
- name: oidc-custom
  label: Custom SSO
  provider:
    type: custom
    client_id: xxx
    client_secret: xxx
    issuer_url: https://authentik.com
    scopes:
      - email
      - openid
```
Brother, thank you, but the log is still not responding
Click the oidc authentication button in the browser, still no response

**Comment by vitaaaaa1** [comment]
Other programs to configure the oidc will require more parameters than issuer_url
Like other parameters, like
token_url
userdata_url
oauth_callback_url
Am I missing any parameters, but I don't see any other parameters that need to be configured on the official website

**Comment by Eugeny** [comment]
Surely you're getting _some_ output?

<img width="678" alt="Screenshot 2024-09-30 at 12 22 04" src="https://github.com/user-attachments/assets/f561411c-01fa-4f62-83bf-f9d1cbed748d">

**Comment by vitaaaaa1** [comment]
```
root@test-sys-lab-05:~/wargate/data# docker compose up 
WARN[0000] /root/wargate/docker-compose.yml: `version` is obsolete 
[+] Running 1/0
 ✔ Container wargate-warpgate-1  Created                                                                                                                                                              0.0s 
Attaching to warpgate-1
warpgate-1  | 10:30:45  INFO Warpgate version=0.10.2
warpgate-1  | 10:30:45  INFO Using config: "/data/warpgate.yaml"
warpgate-1  | 10:30:45  INFO --------------------------------------------
warpgate-1  | 10:30:45  INFO Warpgate is now running.
warpgate-1  | 10:30:45  INFO Accepting SSH connections on 0.0.0.0:2222
warpgate-1  | 10:30:45  INFO Accepting HTTP connections on https://0.0.0.0:8888
warpgate-1  | 10:30:45  INFO Accepting MySQL connections on 0.0.0.0:33306
warpgate-1  | 10:30:45  INFO --------------------------------------------
warpgate-1  | 10:30:45 DEBUG Database cleaned up, next in 60480s
warpgate-1  | 10:30:45  INFO Listening address=0.0.0.0:2222
warpgate-1  | 10:30:45  INFO Listening address=0.0.0.0:8888


docker ps --no-trunc
d3a81f0efca202605f80b30431f4fc32ad0fd96ce0acb84fe6d24fbb5cee9950   ghcr.io/warp-tech/warpgate   "warpgate --config /data/warpgate.yaml --debug run"   7 hours ago   Up 56 seconds                0.0.0.0:2222->2222/tcp, :::2222->2222/tcp, 0.0.0.0:8888->8888/tcp, :::8888->8888/tcp, 0.0.0.0:33306->33306/tcp, :::33306->33306/tcp   wargate-warpgate-1
```

**Comment by Eugeny** [comment]
Now try doing an OIDC login and see what gets logged

**Comment by cosmoswafer** [comment]
I have a similar issue with version 0.11.0. When I visit `/@warpgate/api/sso/providers/custom/start?next=%2F`, I receive the following error messages. I have tried both with and without the trailing slash (/):

```
Provider discovery error: Validation error: unexpected issuer URI `https://example.site.com` (expected `https://example.site.com/`)
```

**Comment by Eugeny** [comment]
@cosmoswafer what's your SSO configuration like?

**Comment by cosmoswafer** [comment]
Here it is, I have tried both with and without the trailing slash (/)

```
sso_providers:
- name: custom
  label: NextCloud
  provider:
    type: custom
    client_id: xxxxxxxxxx
    client_secret: xxxxxxxxxx
    issuer_url: https://example.site.com/
    scopes: ["email"]
```
