### ISSUE TITLE
SSO Validation error: unexpected issuer URI 

### ISSUE THREAD

**Issue by hdhog** [warp-tech/warpgate#1099]
I use Authelia as oauth provider

warpgate config
```yaml

sso_providers:
  - name: custom
    label: SSO
    provider:
      type: custom
      client_id: wg
      client_secret: 'secert'
      issuer_url: https://login.example.com/
      scopes:
        - openid
        - email
```

in web received HTTP 500

```
GET https://wg.example.com/@warpgate/api/sso/providers/custom/start?next=/@warpgate#/
```

```
provider discovery error: Validation error: unexpected issuer URI `https://login.example.com` (expected `https://login.example.com/`)
```

```
~$ warpgate --version
warpgate 0.11.0
```
