### ISSUE TITLE
MySQL Session not being recorded

### ISSUE THREAD

**Issue by mudasirmirza** [warp-tech/warpgate#1127]
Hi,

I am testing out this cool project which is great.

I have below config at `/etc/warpgate.yaml`

```yaml
sso_providers: []
recordings:
  enable: true
  path: /mnt/warpgate/appdata/recordings
external_host: null
database_url: sqlite:/mnt/warpgate/appdata/db
ssh:
  enable: true
  listen: 0.0.0.0:2222
  external_port: null
  keys: /mnt/warpgate/appdata/ssh-keys
  host_key_verification: prompt
  inactivity_timeout: 5m
http:
  enable: true
  listen: 0.0.0.0:8888
  external_port: null
  certificate: /mnt/warpgate/appdata/tls.certificate.pem
  key: /mnt/warpgate/appdata/tls.key.pem
  trust_x_forwarded_headers: false
  session_max_age: 30m
  cookie_max_age: 1day
mysql:
  enable: true
  listen: 0.0.0.0:33306
  external_port: null
  certificate: /mnt/warpgate/appdata/tls.certificate.pem
  key: /mnt/warpgate/appdata/tls.key.pem
postgres:
  enable: true
  listen: 0.0.0.0:55432
  external_port: null
  certificate: /mnt/warpgate/appdata/tls.certificate.pem
  key: /mnt/warpgate/appdata/tls.key.pem
log:
  retention: 7days
  send_to: null
config_provider: database
```

I am using latest release and copied the file at `/usr/bin/warpgate` and then did `chmod +x /usr/bin/warpgate` and then ran the setup `warpgate setup` and then started the process using `warpgate --config /etc/warpgate.yaml run`

Then using the WebUI I added a Role and the added a User and then added a MySQL target.

I am able to use WarpGate to connect to our MySQL server but I am unable to find any recordings at `/mnt/warpgate/rappdata/recordings`

Nothing showing up in the logs also.

Any help will be appreciated.

Regards.
