### ISSUE TITLE
SSO Google connection failed in version 0.12.0

### ISSUE THREAD

**Issue by khalangy** [warp-tech/warpgate#1173]
Hi,

I installed the version 0.12.0 on one of my warpgate server and SSO not working on this version, it was working on v0.10.2.

Without changing configuration I have this error when I clic on SSO Login button 

```
API error: no valid Host header found and `external_host` config option is not set
```
I tried to add the external_host in the configuration but I have an error with Google 

```
Error 400: redirect_uri_mismatch

You can't connect to this app, because it doesn't comply with Google's OAuth 2.0 policy.

If you are the app's developer, register the redirect URI in the Google Cloud console.
Request details: redirect_uri=https://mywarpgate.example.com:8888/@warpgate/api/sso/return flowName=GeneralOAuthFlow
```
I tried to add :8888 in the redirect URI on Google OAuth but after I have SSL issues.

There is my SSO config
```
sso_providers:
- name: google
  label: Login SSO Google
  provider:
    type: google
    client_id: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com"
    client_secret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
external_host: mywarpgate.example.com
```
I have apache with proxy path config 

Is there something wrong in my conf ? 

I have another server in version 0.10.2 and it works.

Thanks

Best regards 
Moka
