### ISSUE TITLE
Keycloack auth problem (CA issue)

### ISSUE THREAD

**Issue by lifespirit** [warp-tech/warpgate#1208]
Hello. I have CA problem with custom SSO auth (keycloak).

What I do:
1. I create self-provided CA and then I create a server certificate for warpgate.
2. I install nginx. warpgate installed behind nginx
3. I add CA cert to trusted cerrs

Now I get CA error anyway.

For test I add warpgate and keycloak certs to trusted store. Thet don't help. Then I conpile warpgate self for test. That don't help too. Warpgate don't trust my self-signed CA anyway.

Nginx config:

```
server {
  listen 443 quic reuseport;
  listen [fd00:16::3]:443 quic reuseport;
  listen 443 ssl;
  listen [fd00:16::3]:443 ssl;
  server_name  _;
  root /srv/http/warpgate;

  access_log  /var/log/nginx/warpgate.access combined;
  error_log   /var/log/nginx/warpgate.error error;
  ssl_certificate /etc/nginx/cert.crt;
  ssl_certificate_key /etc/nginx/cert.key;

  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers on;
  ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
  ssl_session_timeout  10m;
  ssl_session_cache shared:SSL:10m;
  ssl_session_tickets on;
  ssl_stapling on;
  ssl_stapling_verify on;

  server_tokens off;

  add_header Alt-Svc 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000';

  location / {
    proxy_pass https://127.0.0.1:8888;
    proxy_redirect off;
    proxy_cache off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host warpgate.sip3.public;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location ~* ^/assets/(logo-in-circle.svg|fonts/Lato-Regular.woff2|fonts/Lato-Medium.woff2|fonts/Lato-Regular.woff)$ {
    root        /srv/http/warpgate;
  }

  location ~* ^/auth/(js/.+|realms/.+|resources/.+|robots.txt)$ {
    proxy_pass https://auth.sip3.internal:8090;
    proxy_http_version  1.1;
    proxy_set_header Host warpgate.sip3.public;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Port $server_port;
  }

}
```

Warpgate config:

```
sso_providers:
  - name: keycloak
    label: Keycloak
    provider:
      type: custom
      client_id: warpgate
      client_secret: xxx
      issuer_url: https://warpgate.sip3.public/auth/realms/internal
      scopes: ["email"]
recordings:
  enable: true
  path: /var/lib/warpgate/recordings
external_host: null
database_url: sqlite:/var/lib/warpgate/db
ssh:
  enable: true
  listen: 0.0.0.0:2222
  external_port: null
  keys: /var/lib/warpgate/ssh-keys
  host_key_verification: prompt
  inactivity_timeout: 5m
  keepalive_interval: null
http:
  enable: true
  listen: 0.0.0.0:8888
  external_port: 443
  certificate: /var/lib/warpgate/tls.certificate.pem
  key: /var/lib/warpgate/tls.key.pem
  trust_x_forwarded_headers: true
  session_max_age: 30m
  cookie_max_age: 1day
mysql:
  enable: true
  listen: 0.0.0.0:33306
  external_port: null
  certificate: /var/lib/warpgate/tls.certificate.pem
  key: /var/lib/warpgate/tls.key.pem
postgres:
  enable: true
  listen: 0.0.0.0:55432
  external_port: null
  certificate: /var/lib/warpgate/tls.certificate.pem
  key: /var/lib/warpgate/tls.key.pem
log:
  retention: 7days
  send_to: null
config_provider: database
```

Curl to warpgate, nginx and keycloak work great. how can I get warpgate to trust my CA?
