### ISSUE TITLE
Warpgate Always Affixes Port To SSO URI

### ISSUE THREAD

**Issue by jasonlaguidice** [warp-tech/warpgate#1252]
I'm using the latest nightly as of February 12th. It shows v0.13.0 at the login page.

I have configured Authentik to be used with Warpgate. Warpgate is placed behind a Cloudflare proxy. Warpgate always seems to add `:8888` to the SSO redirect URI - regardless of `external_host` setting

Warpgate is accessible successfully through the Cloudflare tunnel at port 443 and login with typical username/password works.

If I manually add `:443` to `external_host` I get the message at boot that external_host contains a port and will be ignored... and it still appends `:8888` to the redirect URI it attempts to use.

If I change `http.listen` to listen on port 443 (which isn't necessary due to the Cloudflare tunnel anyway) and adjust the tunnel accordingly it DOES work - but this isn't ideal as it should probably work on any arbitrary port or the redirect URI should be built from external_host (without the port) or should be able to be manually configured.

(Side note/issue: `external_host` MUST be before `sso_providers` in the config else seems it will be ignored)

Example config:
```
external_host: warpgate.domain.com
sso_providers:
  - name: custom
    label: Authentik Login
    auto_create_users: true
    provider:
      type: custom
      client_id: your_client_id
      client_secret: your_client_secret
      issuer_url: https://auth.domain.com/application/o/warpgate/
      scopes:
        - email
        - openid
      role_mappings:
        Admins: 'warpgate:admin'
recordings:
  enable: true
  path: /var/lib/warpgate/recordings
database_url: sqlite:/var/lib/warpgate/db
ssh:
  enable: true
  listen: '[::]:2222'
  external_port: null
  keys: /var/lib/warpgate/ssh-keys
  host_key_verification: prompt
  inactivity_timeout: 5m
  keepalive_interval: null
http:
  enable: true
  listen: '[::]:8888'
  external_port: null
  certificate: /var/lib/warpgate/tls.certificate.pem
  key: /var/lib/warpgate/tls.key.pem
  trust_x_forwarded_headers: true
  session_max_age: 30m
  cookie_max_age: 1day
mysql:
  enable: false
  listen: '[::]:33306'
  external_port: null
  certificate: /var/lib/warpgate/tls.certificate.pem
  key: /var/lib/warpgate/tls.key.pem
postgres:
  enable: false
  listen: '[::]:55432'
  external_port: null
  certificate: /var/lib/warpgate/tls.certificate.pem
  key: /var/lib/warpgate/tls.key.pem
log:
  retention: 7days
  send_to: null
config_provider: database
```

One last quick question to tack on, I guess. Are there builds available for 0.14? The docs state `auto_create_users` can be used in 0.14 and higher but the nightly is only 0.13 and, unsurprisingly I guess, `auto_create_users` does not work.
