### ISSUE TITLE
Cannot use role_mappings in SSO

### ISSUE THREAD

**Issue by Zegorax** [warp-tech/warpgate#1283]
Ciao everyone,

I'm having some troubles using the `role_mappings` feature mentioned in the documentation. 

Whatever I put as mappings, the roles will never be matched in Warpgate. For context, here is the Warpgate (v0.13.3) configuration:

```
sso_providers:
  - name: SSO
    label: SSO
    auto_create_users: true
    provider:
      type: custom
      client_id: foo
      client_secret: bar
      issuer_url: https://foobar/o/warpgate/
      scopes:
        - email
        - openid
        - profile
      role_mappings:
        WARPGATE-ADMIN-ACCESS: 'warpgate:admin'
```

And here is the responding OIDC request :

```
{
    "iss": "https://foobar/o/warpgate/",
    "sub": "11",
    "aud": "foo",
    "exp": 1741679668,
    "iat": 1741677868,
    "auth_time": 1741677868,
    "acr": "goauthentik.io/providers/oauth2/default",
    "email": "foobar@foo.com",
    "email_verified": true,
    "name": "Foo Bar",
    "given_name": "Foo Bar",
    "preferred_username": "foo.bar",
    "nickname": "foo.bar",
    "groups": [
        "WARPGATE-ACCESS",
        "WARPGATE-ADMIN-ACCESS",
    ]
}
```

Because nothing was working, I've also put the groups inside the top-level "claims" property, without success as well.

```
{
    "iss": "https://foobar/o/warpgate/",
    "sub": "11",
    "aud": "foo",
    "exp": 1741679668,
    "iat": 1741677868,
    "auth_time": 1741677868,
    "acr": "goauthentik.io/providers/oauth2/default",
    "email": "foobar@foo.com",
    "email_verified": true,
    "claims": [
        "WARPGATE-ACCESS",
        "WARPGATE-ADMIN-ACCESS",
    ],
    "name": "Foo Bar",
    "given_name": "Foo Bar",
    "preferred_username": "foo.bar",
    "nickname": "foo.bar",
    "groups": [
        "WARPGATE-ACCESS",
        "WARPGATE-ADMIN-ACCESS",
    ]
}
```
