### ISSUE TITLE
Cannot seem to get OTP working in WebUI

### ISSUE THREAD

**Issue by bram-pkg** [warp-tech/warpgate#159]
Is this functionality supposed to work?

I am using the following configuration:

```yaml
  # User for Bram
  - username: bram
    credentials:
      - type: password
        hash: "argon hash here"
      - type: publickey
        key: "public key here"
      - type: otp
        key: ...
    require: [publickey, otp]
    roles:
      - "warpgate:admin"

```
