### ISSUE TITLE
Warpgate not showing 2 HTTP endpoints with same IP but different port

### ISSUE THREAD

**Issue by ngjames** [warp-tech/warpgate#224]
**Expected Behavior:** 
Showing 2 HTTP endpoints with the same IP but different port simultaneously in the dashboard
**Current Behavior:** 
Only the first endpoints included in the file of the above type is shown

**Steps to reproduce:**
append the following to warpgate.yaml
```
- allow_roles:
  - warpgate:admin
  - user
  http: [redacted]
  name: svr_10
- allow_roles:
  - warpgate:admin
  - user
  http:
    tls:
      verify: false
    url: [redacted]
  name: svr_7
```
