### ISSUE TITLE
Spaces in ssh target name

### ISSUE THREAD

**Issue by Threnklyn** [warp-tech/warpgate#269]
If you have spaces in your ssh target name like so:
```yaml
targets:
  - name: Dev Server
    allow_roles:
      - "admin"
    ssh:
      host: dev.example.org
      username: john
```
 you get a command looking like this:
![image](https://user-images.githubusercontent.com/6805402/185386273-d19986d8-8e65-4af1-958e-f97525c99926.png)

`ssh thru:Dev Server@ssh.itfspace.net -p 2022`

with the whitespace the command isnt working. Maybe just replace all whitespaces with `_` or `-`?
